version: "3.9"

# Define the networks
networks:
  frontend:
  backend:
  db:

# Define the services/containers to be run
services:
  front: # name of the service
    image: mikelm20/factor-front-end # specify image to build container from
    container_name: factor-front-end
    domainname: mikelm20-factor
    ports:
      - "80:80" # specify port forwarding
    networks:
      - frontend
    restart: always

  back: # name of the service
    env_file: .back.env
    image: mikelm20/factor-back-end # specify image to build container from
    domainname: mikelm20-factor
    container_name: factor-back-end
    ports:
      - "5000:5000" # specify port forwarding
    volumes:
      - ./assets:/factor/assets
      - ./credentials:/factor/credentials
    networks:
      - backend
    depends_on:
      - database
    entrypoint:
      - /bin/sh
      - ./wait-for.sh
      - database:27017
      - --
      - node
      - app.js
    restart: always

  database: # name of the service
    env_file: .db.env
    image: mikelm20/factor-database # specify image to build container from
    domainname: mikelm20-factor
    volumes:
      - ./database/:/data/db
    container_name: database
    networks:
      - backend
      - db
    restart: always

  dbUI:
    env_file: .db-ui.env
    image: mikelm20/mongo-express
    container_name: db-ui
    domainname: mikelm20-factor
    ports:
      - 8081:8081
    networks:
      - db # link this service to the database service
    depends_on:
      - back
