version: "3.9"

# Define the networks
networks:
  frontend:
  backend:
  db:

# Define the services/containers to be run
services:
  front: # name of the first service
    env_file: .front.env
    image: mikelm20/factor-front-end
    container_name: factor-front-end
    ports:
      - "80:80" # specify port forwarding
    networks:
      - frontend
    depends_on:
      - back

  back: #name of the second service
    env_file: .back.env
    image: mikelm20/factor-back-end
    container_name: factor-back-end
    volumes:
      - "./assets:/factor/assets"
      - "./credentials/:/factor/credentials"
    networks:
      - backend
    depends_on:
      - database
    entrypoint:
      - /bin/sh
      - ./wait-for.sh
      - database:27017
      - --
      - node
      - app.js
    restart: always

  database: # name of the third service
    env_file: .db.env
    image: mongo # specify image to build container from
    container_name: database
    volumes:
      - "./database/:/data/db"
      - "./factor-db-init/:/docker-entrypoint-initdb.d/"
    networks:
      - backend
      - db
    restart: always

  dbUI:
    env_file: .db-ui.env
    image: mongo-express
    container_name: db-ui
    ports:
      - 8082:8081
    networks:
      - db # link this service to the database service
    depends_on:
      - back
